//
//  File.swift
//  
//
//  Created by Mark Lilback on 12/11/19.
//

import XCTest
@testable import Rc2Parser

final class RParserTests: XCTestCase {
	/// due to an unknown issue with the RFilter generated by antlr, newlines inside closures cause it to barf. have to not use for the moment.
	let basicText = #"""
	# some code
	z <- 2 + 443.2
	if (z != 445.32) {
		sleep(1)
	}
	rnorm(x,plot(1,"dude"))
	"""#
	let ieqTest = #"""
	value is $f$ dollars
	"""#
	
	func testInlineEquation() throws {
		let parser = RmdParser();
		let chunks = try parser.parse(input: ieqTest)
		XCTAssertEqual(chunks.count, 1)
		XCTAssertEqual(chunks[0].asMarkdown?.inlineChunks.count ?? 0, 1)
	}
	
	func testBasicHighlight() throws {
		
		let parser = RmdParser();
		let str = NSMutableAttributedString(string: basicText)
		try parser.highlight(content: str)
		var keys = [SyntaxElement]()
		str.enumerateAttribute(SyntaxKey, in: NSRange(location: 0, length: basicText.count), options: []) { (keyValue, attrRange, _) in
			guard let element = keyValue as? SyntaxElement else { return }
			keys.append(element)
			 print("got \(element.rawValue) for \(str.attributedSubstring(from: attrRange).string)")
		}
		XCTAssertEqual(keys[0], SyntaxElement.comment)
		XCTAssertEqual(keys[1], SyntaxElement.symbol)
		XCTAssertEqual(keys[2], SyntaxElement.number)
		XCTAssertEqual(keys[3], SyntaxElement.number)
		XCTAssertEqual(keys[4], SyntaxElement.symbol)
		XCTAssertEqual(keys[5], SyntaxElement.number)
		XCTAssertEqual(keys[6], SyntaxElement.functonName)
		XCTAssertEqual(keys[7], SyntaxElement.number)
		XCTAssertEqual(keys[8], SyntaxElement.functonName)
		XCTAssertEqual(keys[9], SyntaxElement.functonName)
		XCTAssertEqual(keys[10], SyntaxElement.number)
	}
	
	static var allTests = [
		("testBasicHighlight", testBasicHighlight),
	]

}
